# Generated by Django 4.2.4 on 2023-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_add_image_1_alter_product_add_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
