# Generated by Django 4.2.4 on 2023-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcolor_product_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='deliver_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='simple_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
