# Generated by Django 4.2.4 on 2023-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_add_image_3_product_deliver_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='detail_1',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
